-- Chuyển đổi dữ liệu cho dashboard Manager quản trị nội dung website.
ALTER TABLE "CAR_VERSION" ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "ACCESSORY" ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "ACCESSORY" ADD COLUMN IF NOT EXISTS type VARCHAR(100) NOT NULL DEFAULT 'OTHER';

ALTER TABLE "CAR_ARTICLE" ALTER COLUMN car_version_id DROP NOT NULL;
ALTER TABLE "CAR_ARTICLE" ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "CAR_ARTICLE" ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "CAR_ARTICLE" ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

DROP TABLE IF EXISTS "ACCESSORY_INVENTORY";
ALTER TABLE "DEALERSHIP" DROP COLUMN IF EXISTS accessory_quantity;
