server:
  port: ${API_GATEWAY_PORT:8090}
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    reactor.netty: DEBUG
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: operation-user-ws-route
              uri: ws://${OPERATION_SERVICE_HOST:operation-service}:${OPERATION_SERVICE_PORT:8091}
              predicates:
                - Path=/user/chat/ws/**
              filters:
                - StripPrefix=1
            - id: operation-user-route
              uri: http://${OPERATION_SERVICE_HOST:operation-service}:${OPERATION_SERVICE_PORT:8091}
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1

            - id: car-route
              uri: http://${OPERATION_SERVICE_HOST:operation-service}:${OPERATION_SERVICE_PORT:8091}
              predicates:
                - Path=/car/**
              filters:
                - StripPrefix=1

            - id: operation-service-route
              uri: http://${OPERATION_SERVICE_HOST:operation-service}:${OPERATION_SERVICE_PORT:8091}
              predicates:
                - Path=/operation/**
              filters:
                - StripPrefix=1

            - id: ai-service-route
              uri: http://${AI_SERVICE_HOST:ai-service}:${AI_SERVICE_PORT:8094}
              predicates:
                - Path=/ai/**
              filters:
                - StripPrefix=1

            - id: chat-service-route
              uri: http://${CHAT_SERVICE_HOST:chat-service}:${CHAT_SERVICE_PORT:8095}
              predicates:
                - Path=/chat/**
              filters:
                - StripPrefix=1

            - id: analysis-service-route
              uri: http://${ANALYSIS_SERVICE_HOST:analysis-service}:${ANALYSIS_SERVICE_PORT:8096}
              predicates:
                - Path=/analysis/**
              filters:
                - StripPrefix=1

            - id: notification-service-route
              uri: http://${NOTIFICATION_SERVICE_HOST:notification-service}:${NOTIFICATION_SERVICE_PORT:8097}
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1
